version: 2
jobs:
  build:
    branches:
      only:
        - edit
    docker:
      # specify the version you desire here
      - image: circleci/node:8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "website/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install --prefix website

      - save_cache:
          paths:
            - website/node_modules
          key: v1-dependencies-{{ checksum "website/package.json" }}

      - run:
          name: Publish
          command: |
            git config --global user.email "eli.segal@gmail.com"
            git config --global user.name "rockem"
            echo "machine github.com login rockem password $GITHUB_TOKEN" > ~/.netrc
            GIT_USER=rockem npm run publish-gh-pages --prefix website
